// Deterministic sample data so the dashboard is fully explorable without a
// live backend (Demo Mode). Mirrors realistic post-discharge scenarios.
import type {
  AnalyticsSummary,
  Escalation,
  OutreachSession,
  Patient,
} from "./types";

const now = Date.now();
const hrs = (h: number) => new Date(now - h * 3600_000).toISOString();
const days = (d: number) => new Date(now - d * 86400_000).toISOString();
const inDays = (d: number) => new Date(now + d * 86400_000).toISOString();
const dob = (y: number, m: number, d: number) =>
  new Date(Date.UTC(y, m - 1, d)).toISOString().slice(0, 10);

export const mockPatients: Patient[] = [
  {
    id: "p-1001",
    epic_patient_id: "EPIC-88213",
    mrn: "MRN-44021",
    first_name: "Eleanor",
    last_name: "Whitfield",
    phone: "+14155550142",
    date_of_birth: dob(1948, 3, 14),
    risk_score: 87,
    risk_level: "high",
    created_at: days(2),
  },
  {
    id: "p-1002",
    epic_patient_id: "EPIC-88240",
    mrn: "MRN-44102",
    first_name: "Marcus",
    last_name: "Delgado",
    phone: "+14155550199",
    date_of_birth: dob(1955, 11, 2),
    risk_score: 73,
    risk_level: "high",
    created_at: days(3),
  },
  {
    id: "p-1003",
    epic_patient_id: "EPIC-88301",
    mrn: "MRN-44210",
    first_name: "Priya",
    last_name: "Nair",
    phone: "+14155550110",
    date_of_birth: dob(1962, 6, 28),
    risk_score: 54,
    risk_level: "medium",
    created_at: days(4),
  },
  {
    id: "p-1004",
    epic_patient_id: "EPIC-88355",
    mrn: "MRN-44288",
    first_name: "Walter",
    last_name: "Osei",
    phone: "+14155550173",
    date_of_birth: dob(1940, 1, 9),
    risk_score: 91,
    risk_level: "high",
    created_at: days(1),
  },
  {
    id: "p-1005",
    epic_patient_id: "EPIC-88390",
    mrn: "MRN-44312",
    first_name: "Dolores",
    last_name: "Ackerman",
    phone: "+14155550188",
    date_of_birth: dob(1958, 9, 21),
    risk_score: 41,
    risk_level: "medium",
    created_at: days(5),
  },
  {
    id: "p-1006",
    epic_patient_id: "EPIC-88412",
    mrn: "MRN-44390",
    first_name: "Hiroshi",
    last_name: "Tanaka",
    phone: "+14155550155",
    date_of_birth: dob(1971, 4, 4),
    risk_score: 22,
    risk_level: "low",
    created_at: days(6),
  },
  {
    id: "p-1007",
    epic_patient_id: "EPIC-88455",
    mrn: "MRN-44455",
    first_name: "Grace",
    last_name: "Okonkwo",
    phone: "+14155550166",
    date_of_birth: dob(1966, 12, 12),
    risk_score: 33,
    risk_level: "low",
    created_at: days(7),
  },
  {
    id: "p-1008",
    epic_patient_id: "EPIC-88501",
    mrn: "MRN-44510",
    first_name: "Samuel",
    last_name: "Brennan",
    phone: "+14155550177",
    date_of_birth: dob(1953, 2, 19),
    risk_score: 68,
    risk_level: "medium",
    created_at: days(2),
  },
];

export const mockEscalations: Escalation[] = [
  {
    id: "e-2001",
    session_id: "s-3001",
    patient_id: "p-1004",
    severity: "urgent",
    reason:
      "Patient reports sudden shortness of breath at rest and a 4 lb weight gain over 48 hours.",
    symptoms_flagged: ["dyspnea_at_rest", "rapid_weight_gain", "ankle_edema"],
    notified_at: hrs(1),
    resolved_at: null,
    resolved_by: null,
    created_at: hrs(1),
  },
  {
    id: "e-2002",
    session_id: "s-3002",
    patient_id: "p-1001",
    severity: "high",
    reason: "Has not filled discharge diuretic; reports mild ankle swelling.",
    symptoms_flagged: ["medication_nonadherence", "ankle_edema"],
    notified_at: hrs(5),
    resolved_at: null,
    resolved_by: null,
    created_at: hrs(5),
  },
  {
    id: "e-2003",
    session_id: "s-3003",
    patient_id: "p-1002",
    severity: "high",
    reason: "Persistent productive cough and low-grade fever on day 3 post-pneumonia.",
    symptoms_flagged: ["fever", "productive_cough"],
    notified_at: hrs(9),
    resolved_at: null,
    resolved_by: null,
    created_at: hrs(9),
  },
  {
    id: "e-2004",
    session_id: "s-3004",
    patient_id: "p-1003",
    severity: "medium",
    reason: "Unsure how to use new inhaler; requesting teaching.",
    symptoms_flagged: ["medication_confusion"],
    notified_at: days(1),
    resolved_at: null,
    resolved_by: null,
    created_at: days(1),
  },
  {
    id: "e-2005",
    session_id: "s-3005",
    patient_id: "p-1008",
    severity: "medium",
    reason: "Missed cardiology follow-up; needs help rescheduling.",
    symptoms_flagged: ["missed_followup"],
    notified_at: days(2),
    resolved_at: days(1),
    resolved_by: "coordinator@careguard.health",
    created_at: days(2),
  },
];

export const mockSessions: Record<string, OutreachSession[]> = {
  "p-1004": [
    {
      id: "s-3004a",
      patient_id: "p-1004",
      discharge_id: "d-9004",
      scheduled_at: days(1),
      started_at: days(1),
      completed_at: days(1),
      channel: "voice",
      status: "completed",
      outreach_number: 1,
      twilio_call_sid: "CA-demo-0001",
      created_at: days(1),
    },
    {
      id: "s-3001",
      patient_id: "p-1004",
      discharge_id: "d-9004",
      scheduled_at: hrs(1),
      started_at: hrs(1),
      completed_at: hrs(1),
      channel: "voice",
      status: "completed",
      outreach_number: 2,
      twilio_call_sid: "CA-demo-0002",
      created_at: hrs(1),
    },
    {
      id: "s-future",
      patient_id: "p-1004",
      discharge_id: "d-9004",
      scheduled_at: inDays(2),
      started_at: null,
      completed_at: null,
      channel: "voice",
      status: "scheduled",
      outreach_number: 3,
      twilio_call_sid: null,
      created_at: hrs(1),
    },
  ],
  "p-1001": [
    {
      id: "s-3002",
      patient_id: "p-1001",
      discharge_id: "d-9001",
      scheduled_at: hrs(5),
      started_at: hrs(5),
      completed_at: hrs(5),
      channel: "voice",
      status: "completed",
      outreach_number: 1,
      twilio_call_sid: "CA-demo-0003",
      created_at: hrs(5),
    },
    {
      id: "s-3002b",
      patient_id: "p-1001",
      discharge_id: "d-9001",
      scheduled_at: inDays(1),
      started_at: null,
      completed_at: null,
      channel: "voice",
      status: "scheduled",
      outreach_number: 2,
      twilio_call_sid: null,
      created_at: hrs(5),
    },
  ],
};

export function mockSummary(): AnalyticsSummary {
  const open = mockEscalations.filter((e) => !e.resolved_at);
  return {
    total_patients: mockPatients.length,
    high_risk_patients: mockPatients.filter((p) => p.risk_level === "high").length,
    open_escalations: open.length,
    urgent_escalations: open.filter((e) => e.severity === "urgent").length,
    generated_at: new Date(now).toISOString(),
  };
}

export function sessionsFor(patientId: string): OutreachSession[] {
  return mockSessions[patientId] ?? [];
}
